>P1;SEQUENCE1

------------QSLG---IRIVGYV-GTAHPGEAS------------GIYVKSIIPGSA
AYHNGQ-IQVNDKIVAVDGVNIQG-FANQDVVEVLRN-AG---QVVHLTLVRRK------
-------------------
*
>P1;SEQUENCE2

------------QSLG---IRIVGYV-GTAHPGEAS------------GIYVKSIIPGSA
AYHNGQ-IQVNDKIVAVDGVNIQG-FANQDVVEVLRN-AG---QVVHLTLVRRK------
-------------------
*
>P1;SEQUENCE3

------------SGLG---LSIVGG------KDTP---------LDA--IVIHEVYEEGA
AARDGR-LWAGDQILEVNGVDLRS-SSHEEAITALRQTP-----QKVRLVVYRDE-----
-------------------
*
>P1;SEQUENCE4

------------RGLG---LSIVG------KRSGS-------------GVFISDIVKGGA
ADLDGR-LIRGDQILSVNGEDMRH-ASQETVATILKCVQ-----GLVQLEIGRLR-----
-------------------
*
>P1;SEQUENCE5

------------DALG---ISIAGG------KGSP---------LGDIPIFIAMIQANGV
AARTQK-LKVGDRIVSINGQPLDG-LSHTDAVNLLKNAF-----GRIILQVVADT-----
-------------------
*
>P1;SEQUENCE6

------------SGLG---MGLIDG------MHTP---------LGAQGLYIQTLLPGSP
AASDGR-LSLGDQILEVNGSSLRG-VSYMRAVDLIRHGG-----KKMRFLVAKSD-----
-------------------
*
>P1;SEQUENCE7

------------EPLG----ATIRR------DEHSGAVVV------------ARIMRGGA
ADRSGL-VHVGDELREVNGIAVLH-KRPDEISQILA-QS----QGSITLKIIPAT-----
-------------------
*
>P1;SEQUENCE8

------------HFLG---ISIVGQ---SNDRGDG-------------GIYIGSIMKGGA
VAADGR-IEPGDMLLQVNDVNFEN-MSNDDAVRVLREIVS---QTGPISLTVAKCW----
-------------------
*
>P1;SEQUENCE9

------------NFLG---ISIVGQ---SNERGDG-------------GIYIGSIMKGGA
VAADGR-IEPGDMLLQVNDMNFEN-MSNDDAVRVLRDIVH---KPGPIVLTVAKCW----
-------------------
*
>P1;SEQUENCE10

------------NFLG---ISIVGQ---SNERGDG-------------GIYIGSIMKGGA
VAADGR-IEPGDMLLQVNEINFEN-MSNDDAVRVLREIVH---KPGPITLTVAKCW----
-------------------
*
>P1;SEQUENCE11

------------PELG---FSISGG------VGG--RGNPFRPD--DDGIFVTRVQPEGP
ASKL---LQPGDKIIQANGYSFIN-IEHGQAVS-LLKTF-----HNAVDLIIVREV----
-------------------
*
>P1;SEQUENCE12

------------QS-----VEIPGG------GTEG--------------YHVLRVQENSP
GHRAGL-EPFFDFIVSINGSRLNK--DNDTLKDLLKANV----EKPVKMLIYSSK-----
-------------------
*
>P1;SEQUENCE13

------------GPLG---ITISGT------EEPFDP------------IIISSLTKGGL
AERTGA-IHIGDRILAINSSSLKG-KPLSEAIHLLQ-MA----GETVTLKIKKQT-----
-------------------
*
>P1;SEQUENCE14

------------RGLG---CSISSG------PIQ------------KPGIFVSHVKPGSL
SAEVG--LETGDQIVEVNGIDFTN-LDHKEAVNVLKSSR-----SLTISIVAGA------
-------------------
*
>P1;SEQUENCE15

------------KYIGIRMMSLTSSKAKELKDRHRDFP------DVLSGAYIIEVIPDTP
AEAGG--LKENDVIISINGQSVVT---ANDVSDVIKKE------NTLNMVVRRGN-----
-------------------
*
>P1;SEQUENCE16

------------RFIGIRMRTITPSLVEELKAANPDFP------AVSSGIYVQEVVPNSP
SQRGG--IQDGDIIVKVNGRPLAD---SSELQEAVLNE------SSLLLEVRRGN-----
-------------------
*
>P1;SEQUENCE17

------------KGLG---FSIVGG------KDSI---------YGPIGIYVKSIFAGGA
AAADGR-LQEGDEILELNGESMAG-LTHQDALQKFKQAKK----GLLTLTVRTRL-----
-------------------
*
>P1;SEQUENCE18

----CVIIQKDDNGFG---LTVSGD------NPVF----------------VQSVKEDGA
AMRAG--VQTGDRIIKVNGTLVTH-SNHLEVVKLIRSG-----SYVALTVQGRPPGS---
-------------------
*
>P1;SEQUENCE19

------------EGLG---FNVMGG------KEQNSPIYI------------SRIIPGGV
AERHGG-LKRGDQLLSVNGVSVEG-EHHEKAVELLK-AA----KDSVKLVVRYTP-----
-------------------
*
>P1;SEQUENCE20

----VVELPKTEEGLG---FNIMGG------KEQNSPIYI------------SRIIPGGI
ADRHGG-LKRGDQLLSVNGVRVEG-EHHEKAVELLK-AA----QGKVKLVVRYTP-----
-------------------
*
>P1;SEQUENCE21

------------EQLG---IKLVRR------VDEP-------------GVFIFNVLNGGV
ADRHGQ-LEENDRVLAINGHDLRF-GSPESAAHLIQASE-----RRVHLVVSRQV-----
-------------------
*
>P1;SEQUENCE22

--EQFCVRIEKNPGLG---FSISGG------ISG--QGNPFKPS--DKGIFVTRVQPDGP
ASNL---LQPGDKILQANGHSFVH-MEHEKAVL-LLKSF-----QNTVDLVIQREL----
-------------------
*
>P1;SEQUENCE23

------------RGFG---FTVVGG------DEPD------------EFLQIKSLVLDGP
AALDGK-METGDVIVSVNDTCVLG-HTHAQVVKIFQSIPI---GASVDLELCRGY-----
-------------------
*
>P1;SEQUENCE24

------------TGFG---FRILGG------NEPG------------EPIYIGHIVPLGA
ADTDGR-LRSGDELICVDGTPVIG-KSHQLVVQLMQQAAK---QGHVNLTVRRKV-----
-------------------
*
>P1;SEQUENCE25

------------KGFG---FSLRGG------REYN------------MDLYVLRLAEDGP
AERCGK-MRIGDEILEINGETTKN-MKHSRAIELIKNG-----GRRVRLFLRRGD-----
-------------------
*
>P1;SEQUENCE26

------------EGFGFVIISSLNR------PESGATITVP--------HKIGRIIDGSP
ADRCAK-LKVGDRILAVNGQSIIN-MPHADIVKLIK-DA----GLSVTLRIIPQE-----
-------------------
*
>P1;SEQUENCE27

------------KGFG---FSIRGG------REYK------------MDLYVLRLAEDGP
AIRNGR-MRVGDQIIEINGESTRD-MTHARAIELIKSG-----GRRVRLLLKRGT-----
-------------------
*
>P1;SEQUENCE28

------------EHLG----VTFRV------E--GGELVI------------ARILHGGM
VAQQGL-LHVGDIIKEVNGQPVGS-D-PRALQELLR-SA----SGSVILKILPSY-----
-------------------
*
>P1;SEQUENCE29

------------GGLG---FSVVGL------RSEN---------RGELGIFVQEIQEGSV
AHRDGR-LKETDQILAINGQVLDQTITHQQAISILQKAK-----DTVQLVIARGS-----
-------------------
*
>P1;SEQUENCE30

------------RGLG---FSILDY------QDPIDPANTV--------IVIRSLVPGGI
AEKDGR-LFPGDRLMFVNDINLEN-STLEEAVEALKGAP----SGMVRIGVAKPL-----
-------------------
*
>P1;SEQUENCE31

------------TGLG---LSIVGG------SDTL---------LGA--IIIHEVYEEGA
ACKDGR-LWAGDQILEVNGIDLRK-ATHDEAINVLRQTP-----QRVRLTLYRDE-----
-------------------
*
>P1;SEQUENCE32

------------KGLG---LSIVG------KRNDT-------------GVFVSDIVKGGI
ADADGR-LMQGDQILMVNGEDVRH-ATQEAVAALLKCSL-----GAVTLEVGRVK-----
-------------------
*
>P1;SEQUENCE33

------------DSLG---LSIAGG------VGSP---------LGDVPIFIAMMHPNGV
AAQTQK-LRVGDRIVTICGTSTDG-MTHTQAVNLMKNAS-----GSIEVQVVAGG-----
-------------------
*
>P1;SEQUENCE34

------------DGLG---FSIVGG------YGSP---------HGDLPIYVKTVFAKGA
AAEDGR-LKRGDQIIAVNGQSLEG-VTHEEAVAILKRTK-----GTVTLMVLS-------
-------------------
*
>P1;SEQUENCE35

------------NGYG---FHLHGE------KGKV-------------GQFIRLVEPGSP
AEKSG--LLAGDRLVEVNGENVEK-ETHQQVVSRIRAA-----LNAVRLLVVDPE-----
-------------------
*
>P1;SEQUENCE36

------------NGYG---FNLHSD------KSKP-------------GQFIRAVDPDSP
AEASG--LRAQDRIVEVNGVCMEG-KQHGDVVSAIKGG-----GDEAKLLVVDKE-----
-------------------
*
>P1;SEQUENCE37

------------GGLG---F-------LVKERVSKP------------PVIISDLIRGGA
AEQSGL-IQAGDIILAVNDRPLVD-LSYDSALEVLRG-IA---SETHVVLILRGP-----
-------------------
*
>P1;SEQUENCE38

---EVPLNDSGSAGLG---VSVKGNR-SKENHADL-------------GIFVKSIINGGA
ASKDGR-LRVNDQLIAVNGESLLG-KANQEAMETLRRSMS---TEGNKRGMIQ-------
-------------------
*
>P1;SEQUENCE39

------------DPLGIHVVPFFSS------LSGR-----------ILGLFIRGIEENSR
CKQEGL-FQENECIVKINNVELLD-KTFAQAQDVFRQAMK---SPSVILHVLLPQ-----
-------------------
*
>P1;SEQUENCE40

------------KPLG---FYIRDGS---SVRVTPHG------LEKVPGIFISRLVPGGL
AQSTGL-LAVNDEVLEVNGIEVSG-KSLDQVTDMMIANS-----RNLIITVRPAN-----
-------------------
*
>P1;SEQUENCE41

------------APWG---FRLQGG------KDFN------------MPLTISSLKDGGK
ASQAH--VRIGDVVLSIDGISAQG-MTHLEAQNKIKAC-----TGSLNMTLQRAS-----
-------------------
*
>P1;SEQUENCE42

---ECKLSKQEGQNYG---FFLRIE------KDTD-------------GHLIRVIEEGSP
AEKAG--LLDGDRVLRINGVFVDK-EEHAQVVELVRKS-----GNSVTLLVLDGD-----
-------------------
*
>P1;SEQUENCE43

----VVVIKKGSNGYG---FYLRAG------PEQK-------------GQIIKDIEPGSP
AEAAG--LKNNDLVVAVNGKSVEA-LDHDGVVEMIRKG-----GDQTTLLVLDKE-----
-------------------
*
>P1;SEQUENCE44

---IVTLKKPPGAQLG---FNIRGG------KAS------------QLGIFISKVIPDSD
AHRAG--LQEGDQVLAVNDVDFQD-IEHSKAVEILKTAR-----EISMRVRFFPY-----
-------------------
*
>P1;SEQUENCE45

----EMELLKESDGLG---IQVSGG------RGSK---------RSPHAIVVTQVKEGGA
AHRDGR-LSLGDELLVINGHLLVG-LSHEEAVAILRSAT-----GMVQLVVASKM-----
-------------------
*
>P1;SEQUENCE46

----CVEVLKTSAGLG---LSLDGG------KSSI---------AGDGPLVIKRVYQGGA
AEQAGT-IEAGDEILAINGKPLVG-LVHFDAWNIMKSVPE----GPVQLVIRKH------
-------------------
*
>P1;SEQUENCE47

------------DGFG---FTICCD------SPVR----------------VQAVDSGGP
AERAG--LQQLDTVLQLNERPVEH-WKCVELAHEIRSC-----PSEIILLVWRVV-----
-------------------
*
>P1;SEQUENCE48

------------SGLG---FSIAGG------TDN-------PHIGDDPSIFITKIIPGGA
AAQDGR-LRVNDSILFVNEVDVRE-VTHSAAVEALKEAG-----SIVRLYVMRRK-----
-------------------
*
>P1;SEQUENCE49

----EVKLFKNSSGLG---FSFSREDNLIPEQINGS------------IVRVKKLFPGQP
AAESGK-IDVGDVILKVNGAPLKG-LSQQDVISALRG-TA---PEVSLLLCRPA------
-------------------
*
>P1;SEQUENCE50

----EITLERGNSGLG---FSIAGG------TDN-------PHIGDDSSIFITKIITGGA
AAQDGR-LRVNDCILRVNEADVRD-VTHSKAVEALKEAG-----SIVRLYVKRRK-----
-------------------
*
>P1;SEQUENCE51

----KVVLHRGSTGLG---FNIVGG------EDG-------------EGIFISFILAGGP
ADLSGE-LRKGDRIISVNSVDLRA-ASHEQAAAALKNAG-----QAVTIVAQYRP-----
-------------------
*
>P1;SEQUENCE52

----KIILHKGSTGLG---FNIVGG------EDG-------------EGIFVSFILAGGP
ADLSGE-LRRGDRILSVNGVNLRN-ATHEQAAAALKRAG-----QSVTIVAQYRP-----
-------------------
*
>P1;SEQUENCE53

----TLTIVRQTGGLG---ISIAGG------KGSTP------YKGDDEGIFISRVSEEGP
AARAG--VRVGDKLLEVNGVALQD-AEHHEAVEALRGAG-----AAVQMRVWRER-----
-------------------
*
>P1;SEQUENCE54

----AACLVRSEKGLG---FSIAGG------KGSTP------YRAGDGGIFISRIAEGGA
AHRAGT-LQVGDRVLSINGVDMTE-ARHDHAVSLLTAAS-----PTISLLLERET-----
-------------------
*
>P1;SEQUENCE55

----EICLPRAGGPLG---LSIVGG------SDHSSH----PFGVQDPGVFISKVLPRGL
AARCG--LRVGDRILAVNGQDVRE-ATHQEAVSALLRPC-----LELCLLVRRDP-----
-------------------
*
>P1;SEQUENCE56

----TLVLHRDSGSLG---FNIIGGRPCVDNQDGSS----------SEGIFVSKIVDSGP
AAKEGG-LQIHDRIIEVNGKDLSR-ATHDQAVEAFKTAK-----EPIVVQVLRRT-----
-------------------
*
>P1;SEQUENCE57

---TVLLQKKDSEGFG---FVLRGA------KAQTPIEEFTPTPAFPALQYLESVDEGGV
AWRAG--LRMGDFLIEVNGQNVVK-VGHRQVVNMIRQG-----GNTLMVKVVMVT-----
-------------------
*
>P1;SEQUENCE58

---VAILQKRDHEGFG---FVLRGA------KAETPIEEFTPTPAFPALQYLESVDVEGV
AWRAG--LRTGDFLIEVNGVNVVK-VGHKQVVGLIRQG-----GNRLVMKVVSVT-----
-------------------
*
>P1;SEQUENCE59

------------APWG---FTLKGG------LERG------------EPLIISKIEEGGK
ADSVSSGLQAGDEVIHINEVALS--SPRREAVSLVKGS-----YKTLRLVVRRDV-----
-------------------
*
>P1;SEQUENCE60

------------GGLG---ISIKGG-----RENKM-------------PILISKIFKGLA
ADQTEA-LFVGDAILSVNGEDLSS-ATHDEAVQALKKTG-----KEVVLEVKYMKTHDEA
VQALKKTGKEVVLEVKYMK
*
>P1;SEQUENCE61

------------GGLG---ISIKGG-----KENKM-------------PILISKIFKGLA
ADQTQA-LYVGDAILSVNGADLRD-ATHDEAVQALKRAG-----KEVLLEVKYMR-----
-------------------
*
>P1;SEQUENCE62

------------GGLG---LSIKGG-----AEHGV-------------PVVISKIFKDQA
ADQTEM-LFIGDAVLQVNGINVEN-ATHEEVVHLLRNAG-----DDVTITVEYLR-----
-------------------
*
>P1;SEQUENCE63

------------APWG---FRISGG------RDFH------------TPIIVTKVTERGK
AEAAD--LRPGDIIVAINGQSAEN-MLHAEAQSKIRQS-----ASPLRLQLDRSQ-----
-------------------
*
>P1;SEQUENCE64

--DVQLTKTGDMTDFG---FAVTVQ-----VDEHQHLN----------RIFISDVLPDSL
AYGGG--LRKGNEITSLNGEPVSD-LDIQQMEALFSEKS-----VGLTLVARPVT-----
-------------------
*
>P1;SEQUENCE65

RVEIHKLRQGENLILG---FSIGGG------IDQDPSQNPFSEDKTDKGIYVTRVSEGGP
AEIAG--LQIGDKIMQVNGWDMTM-VTHDQARKRLTKRS-----EEVVRLLVTRQ-----
-------------------
*
>P1;SEQUENCE66

------------ATLG---IAIEGG------ANTR-----------QPLPRIVTIQRGGS
AHNCGQ-LKVGHVILEVNGQTLRG-KEHKEAARIIAEAFKTKERDYIDFLVTEFNEHKEA
ARIIAEAFKTKERDYIDFL
*
>P1;SEQUENCE67

------------FGFG---IAISGG------RDNPHFQSGE------TSIVISDVLKGGP
A--EGQ-LQENDRVAMVNGVSMDN-VEHAFAVQQLRKS-----GKNAKITIRRKK-----
-------------------
*
>P1;SEQUENCE68

------------EEYG---LRLASH------------------------IFVKEISQDSL
AARDGN-IQEGDVVLKINGTVTEN-MSLTDAKTLIERSK-----GKLKMVVQRDE-----
-------------------
*
>P1;SEQUENCE69

------------RGFG---IAVSGG------RDNPHFENGE------TSIVISDVLPGGP
A--DGL-LQENDRVVMVNGTPMED-VLHSFAVQQLRKS-----GKIAAIVVKRPR-----
-------------------
*
>P1;SEQUENCE70

------------RGFG---IAVSGG------HDR---ASG--------SVVVSDVVPGGP
A--EGR-LRTGDHIVMVNGVSVEN-VTSAFAIQILKTC-----TKTANVTVKRPR-----
-------------------
*
